### PR TITLE
5 marketplace

### PR DESCRIPTION
**Pull request by zhuodannychen**
Please review! Haven't tested but there are no compilation errors and the logic looks straightforward.

Thoughts
1). I assume we can only list the RevPass collection on the marketplace. Although it wouldn't be hard to support more collections
2). I don't think we need to take RevPass off the marketplace if it gets rented out. I am thinking if the owner wants to rent it out for two games in a row, then they set startDate and endDate for two weeks. Say hypothetically userA rents it for the first week. The rent status on the frontend would just change. Once userA's term expires, its availability on the market changes again. Now, userB can rent it for the second week. This prevents two listing fees and saves gas from the RevPass owner's point of view.
3). There's some refunding logic that needs to be sorted out if owner unlists while user is still renting.

### CODE REVIEW

**Comment by zhuodannychen** [comment]
Actually just realized it will theoretically not matter which sports pass a user chooses to rent right, since they all serve the same purpose. Not sure if it's needed to list all the RevPass

**Comment by ishandhanani** [comment]
Instead of importing IERC4907, we should import IRevPass to account for UIN functionality

**Comment by ishandhanani** [comment]
Listing struct should include UIN data

**Comment by ishandhanani** [comment]
1. There should not be a listing fee. This should also be removed from the list function 
2. There should be a private listing option for sharing between friends 
 - same as list function but 1 more input (user's wallet address) and a require statement that forces that wallet address
 3. The unlist function need to check that there is no existing user. Or else the owner can receive payment then unlist their sports pass effectively breaking the system

**Comment by zhuodannychen** [comment]
Made changes

**Comment by ishandhanani** [comment]
Based on our walk through I think this is good to merge. If we need to mess with it more (adding confirmation, etc) we can create a new one. 

Good work Danny

**Pull request merged**
